// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCD8nIhwEDxC17G9qLmSCtCKzlzAue5CHU',
    appId: '1:375677900388:web:56ee1388bf513c806c3171',
    messagingSenderId: '375677900388',
    projectId: 'mobile-e-commerce-c14d4',
    authDomain: 'mobile-e-commerce-c14d4.firebaseapp.com',
    storageBucket: 'mobile-e-commerce-c14d4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDftWVC7qNohkaWv_JNwatt6qdu-WR-Rf0',
    appId: '1:375677900388:android:b1df5d3b114c9cb36c3171',
    messagingSenderId: '375677900388',
    projectId: 'mobile-e-commerce-c14d4',
    storageBucket: 'mobile-e-commerce-c14d4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJMzn9Gr_Ke6esd9p1k4TZLFhlEwgTl_E',
    appId: '1:375677900388:ios:c5d9a72e91f4ba166c3171',
    messagingSenderId: '375677900388',
    projectId: 'mobile-e-commerce-c14d4',
    storageBucket: 'mobile-e-commerce-c14d4.appspot.com',
    iosBundleId: 'com.example.mobileECommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJMzn9Gr_Ke6esd9p1k4TZLFhlEwgTl_E',
    appId: '1:375677900388:ios:58ecf7d6f571d9a56c3171',
    messagingSenderId: '375677900388',
    projectId: 'mobile-e-commerce-c14d4',
    storageBucket: 'mobile-e-commerce-c14d4.appspot.com',
    iosBundleId: 'com.example.mobileECommerce.RunnerTests',
  );
}
